console.log("Albert Barkovski ", "24y.o.\n" + "mokausi programavima, nes tai man lb patinkas");
console.log("jadfjdwb,jdbjw\njhdsbfkhdwbjfk fhbwrhfb\ndhbrwhbgfhkfhrwb\nbhfbwrhfb");
console.log("***\n" + "*", "*\n" + "***");
console.log("*\n" + "**\n" + "***");
console.log("labas\n" + "tu\n" + "esi\n" + "geras\n" + "programuotojas");
console.log("+-------+------+");
console.log("|" + "Vardas" + " |" + "Amzius" + "|");
console.log("+-------+------+");
console.log("|" + "Tomas" + "  |" + "25" + "    |");
console.log("|" + "Joe" + "    |" + "49" + "    |");
console.log("|" + "Albert" + " |" + "13" + "    |");
console.log("+-------+------+");
document.querySelector("p").innerHTML = "pumpidap";
